#!/bin/bash
# bridge-ssh.sh — owner-only SSH, reachable ONLY over the tailnet.
#
# What it allows: user `pi` (who has sudo), with the owner's key, from a tailnet address, to
# the bridge's own tailnet address. What it refuses: root login, passwords, keyboard-interactive,
# every kind of forwarding and tunnel, and any connection on the LAN / Wi-Fi / setup AP — sshd
# is not even listening there. The bridge is reachable wherever it has internet, because the
# tailnet is.
#
# Why a supervisor and not ssh.service: sshd needs a concrete ListenAddress, and the tailnet
# address only exists once tailscaled is up. This waits for it, writes a config for exactly that
# address, checks it with `sshd -t`, runs sshd, and restarts it if the address ever changes.
# The host key lives on /data so its fingerprint survives reboots and image updates (the root
# filesystem is read-only and replaced by every update).
set -uo pipefail
KEYS="${BRIDGE_SSH_KEYS:-/etc/netbridge/owner_ssh_authorized_keys}"
HOSTKEY_DIR="${BRIDGE_SSH_HOSTKEY_DIR:-/data/ssh}"
RUNDIR="${BRIDGE_SSH_RUNDIR:-/run/bridge-ssh}"
PRIVSEP="${BRIDGE_SSH_PRIVSEP:-/run/sshd}"
SSHD="${BRIDGE_SSH_SSHD:-/usr/sbin/sshd}"
TSIP_CMD="${BRIDGE_SSH_TSIP_CMD:-tailscale ip -4}"
CHECK_S="${BRIDGE_SSH_CHECK_S:-30}"
ONCE="${BRIDGE_SSH_ONCE:-}"          # tests: write + check the config, then exit
USER_ALLOWED="${BRIDGE_SSH_USER:-pi}"

KEY_DIRECTIVES="AuthorizedKeysFile $KEYS"
STRICT_KEYS=0
if [ -e "${BRIDGE_SIGNATURE_POLICY:-/etc/netbridge/script-signature-v2}" ]; then
  STRICT_KEYS=1
  KEY_VERIFY="${BRIDGE_SIGNATURE_VERIFIER:-/usr/local/bin/bridge-verify-update.py}"
  KEY_PUB="${BRIDGE_SSH_PUBKEY:-/etc/netbridge/script-pubkey.pem}"
  KEY_FLOORS="${BRIDGE_SSH_FLOORS:-/data/overrides/.security-floor}"
  KEY_DIRECTIVES="AuthorizedKeysFile none
AuthorizedKeysCommand /usr/bin/python3 \"$KEY_VERIFY\" owner-keys \"$KEY_PUB\" \"$KEY_FLOORS\" \"$KEYS\"
AuthorizedKeysCommandUser root"
fi
owner_keys_present(){
  if [ "$STRICT_KEYS" = 1 ]; then
    python3 "$KEY_VERIFY" owner-keys "$KEY_PUB" "$KEY_FLOORS" "$KEYS" | grep -q '^[^#]'
  else
    [ -s "$KEYS" ] && grep -q '^[^#]' "$KEYS"
  fi
}

log(){ echo "bridge-ssh: $*" >&2; }

# The bridge's IPv4 on the tailnet: 100.64.0.0/10 and nothing else.
tailnet_ip(){
  $TSIP_CMD 2>/dev/null | head -1 |
    grep -E '^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.[0-9]{1,3}\.[0-9]{1,3}$'
}

ensure_hostkey(){
  mkdir -p "$HOSTKEY_DIR" && chmod 0700 "$HOSTKEY_DIR"
  [ -s "$HOSTKEY_DIR/ssh_host_ed25519_key" ] && return 0
  ssh-keygen -q -t ed25519 -N "" -C "netbridge-host" -f "$HOSTKEY_DIR/ssh_host_ed25519_key" &&
    log "created host key $(ssh-keygen -l -f "$HOSTKEY_DIR/ssh_host_ed25519_key.pub" | cut -d' ' -f2)"
}

write_config(){   # write_config <tailnet-ip>
  mkdir -p "$RUNDIR"
  cat > "$RUNDIR/sshd_config.tmp" <<EOF
# generated by bridge-ssh.sh for $1 — do not edit (see /usr/local/bin/bridge-ssh.sh)
ListenAddress $1
Port 22
AddressFamily inet
HostKey $HOSTKEY_DIR/ssh_host_ed25519_key
PidFile $RUNDIR/sshd.pid
$KEY_DIRECTIVES
PermitRootLogin no
AllowUsers $USER_ALLOWED@100.64.0.0/10
PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
HostbasedAuthentication no
UsePAM yes
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
AllowStreamLocalForwarding no
PermitTunnel no
GatewayPorts no
PermitUserEnvironment no
PermitUserRC no
StrictModes yes
MaxAuthTries 3
MaxSessions 4
MaxStartups 4:50:10
LoginGraceTime 20
ClientAliveInterval 30
ClientAliveCountMax 4
PrintMotd no
Subsystem sftp internal-sftp
LogLevel VERBOSE
EOF
  mv -f "$RUNDIR/sshd_config.tmp" "$RUNDIR/sshd_config"
}

owner_keys_present || { log "no owner key in $KEYS — SSH stays off"; [ -n "$ONCE" ] && exit 2; exec sleep infinity; }
mkdir -p "$PRIVSEP" && chmod 0755 "$PRIVSEP"
ensure_hostkey || { log "could not create a host key on $HOSTKEY_DIR"; exit 1; }

pid=""
trap '[ -n "$pid" ] && kill "$pid" 2>/dev/null; exit 0' TERM INT
while :; do
  ip="$(tailnet_ip)"
  if [ -z "$ip" ]; then sleep 10; [ -n "$ONCE" ] && exit 3; continue; fi
  write_config "$ip"
  if ! "$SSHD" -t -f "$RUNDIR/sshd_config"; then
    log "sshd rejected the generated config — not starting"; [ -n "$ONCE" ] && exit 4; sleep 30; continue
  fi
  [ -n "$ONCE" ] && { log "config OK for $ip"; exit 0; }
  "$SSHD" -D -e -f "$RUNDIR/sshd_config" & pid=$!
  log "listening on $ip:22 — owner key only, tailnet only"
  while kill -0 "$pid" 2>/dev/null; do
    sleep "$CHECK_S"
    [ "$(tailnet_ip)" = "$ip" ] && continue
    log "tailnet address changed — restarting on the new one"; kill "$pid" 2>/dev/null; break
  done
  wait "$pid" 2>/dev/null; pid=""
  sleep 2
done
