import {test,expect} from '@playwright/test';
test('browser preview shows honest states and navigates without overflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Set up your session'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Go live',exact:true})).toBeDisabled();
 await page.screenshot({path:'test-results/studio.png',fullPage:true});
 await expect(page.getByRole('button',{name:/Personas/})).toHaveCount(0);
 await expect(page.getByRole('region',{name:'Meeting checks'})).toBeVisible();
 await expect(page.getByText('0/4 confirmed',{exact:true})).toBeVisible();
 const checks=page.getByRole('table',{name:'Live delivery checks'});
 await expect(checks.getByRole('row')).toHaveCount(5);
 for(const label of ['Your video arriving at bridge','Your voice arriving at bridge','Meeting laptop sees the camera','Meeting audio flowing back']) await expect(checks.getByRole('rowheader',{name:label})).toBeVisible();
 await checks.locator('summary').first().click();
 await expect(checks.getByText('video_arriving',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Connection health',exact:true}).click();
 await expect(page.locator('aside').getByText('Not streaming',{exact:true})).toHaveCount(4);
 await page.getByRole('button',{name:'Close diagnostics'}).click();
 for(const name of ['Bridges','Sessions','Settings']){await page.getByRole('button',{name,exact:true}).first().click();await expect(page.locator('h1')).toBeVisible()}
 await page.setViewportSize({width:960,height:680});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Studio',exact:true}).first().click();
 const action=await page.getByRole('button',{name:'Go live',exact:true}).boundingBox();
 expect(action).not.toBeNull();expect(action!.y+action!.height).toBeLessThanOrEqual(680);
 await page.screenshot({path:'test-results/studio-compact.png',fullPage:true});
 expect(errors).toEqual([]);
});

test('desktop UI unlocks before streaming, handles mute, and ends session',async({page})=>{
 await page.addInitScript(()=>{
  const w=window as any;w.isTauri=true;w.calls=[];w.rejectStart=true;
  const state={signed_in:false,email:'developer@example.test',control_url:'https://fleet.example.test',last_bridge:'room',last_camera:'Test camera',last_mic:'Disconnected microphone',live:false,wanted:false,voice_muted:false,return_on:true,return_gain:'1.0',return_jitter_ms:'250',version:'test'};
  w.__TAURI_INTERNALS__={metadata:{currentWindow:{label:'main'},currentWebview:{label:'main'}},transformCallback:()=>1,unregisterCallback:()=>{},invoke:async(cmd:string,args:any)=>{
   if(cmd!=='engine_request')return 1;
   w.calls.push({path:args.path,body:args.body});
   switch(args.path){
    case '/api/signin-request':return {note:'Check your email for the code.'};
    case '/api/signin-redeem':state.signed_in=true;return {ok:true};
    case '/api/preflight':return {checks:[{label:'Camera',status:'pass',detail:'Listed, capture not yet tested.'},{label:'Receiver',status:'unknown',detail:'Displayed picture not verified.'}]};
    case '/api/support-report':return args.body.submit?{reference:'NB-SUPPORT-42'}:{report:{live:state.live,app_version:'test'},notice:'No recordings or raw logs are uploaded.'};
    case '/api/state':return {...state,bridge_checks:{age_s:1,reachable:true,checks:Object.fromEntries(['video_arriving','voice_arriving','return_audio','client_sees_camera'].map(key=>[key,{ok:true,detail:'Fresh test measurement'}]))}};
    case '/api/bridges':return [{id:'room',name:'Test room',online:true,tailscale_ip:'100.1.2.3'}];
    case '/api/devices':return {video:[{name:'Test camera',index:'0'}],audio:[{name:'Test mic',index:'0'}]};
    case '/api/unlock':return {ok:args.body.pin==='123456',message:'Wrong PIN'};
    case '/api/golive':if(w.rejectStart){w.rejectStart=false;return {_error:'Session expired. Enter the bridge PIN again.'}}state.live=true;state.wanted=true;return {ok:true};
    case '/api/microphone':state.voice_muted=args.body.muted;return {ok:true};
    case '/api/return':state.return_on=args.body.on;return {ok:true};
    case '/api/stop':state.live=false;state.wanted=false;return {ok:true};
    default:return {ok:true};
   }
  }};
 });
 await page.goto('/');
 await page.getByLabel('Work email',{exact:true}).fill('developer@example.test');
 await page.getByRole('button',{name:'Send sign-in code',exact:true}).click();
 await page.getByLabel('Sign-in or invitation code',{exact:true}).fill('test-code');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('button',{name:'Go live',exact:true})).toBeEnabled();
 await expect(page.getByRole('list',{name:'Session setup progress'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Go live',exact:true})).toHaveCount(1);
 await page.screenshot({path:'test-results/studio-ready.png',fullPage:true});
 await page.getByPlaceholder('Enter your bridge PIN').fill('000000');
 await page.getByRole('button',{name:'Go live',exact:true}).click();
 await expect(page.getByText('Wrong PIN',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>(window as any).calls.some((c:any)=>c.path==='/api/golive'))).toBeFalsy();
 await page.getByRole('button',{name:'Check my setup',exact:true}).click();
 await expect(page.getByText('Displayed picture not verified.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Close setup results'}).click();
 await page.getByRole('button',{name:'Get help',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Send a report to your fleet administrator'})).toBeVisible();
 expect(await page.evaluate(()=>(window as any).calls.some((c:any)=>c.path==='/api/support-report'&&c.body.submit))).toBeFalsy();
 await page.getByRole('button',{name:'Send report',exact:true}).click();
 await expect(page.getByText('Sent: NB-SUPPORT-42',{exact:true})).toBeVisible();
 await page.getByPlaceholder('Enter your bridge PIN').fill('123456');
 await page.getByRole('button',{name:'Go live',exact:true}).click();
 await expect(page.getByText('Session expired. Enter the bridge PIN again.',{exact:true})).toBeVisible();
 await page.getByPlaceholder('Enter your bridge PIN').fill('123456');
 await page.getByRole('button',{name:'Go live',exact:true}).click();
 expect(await page.evaluate(()=>(window as any).calls.filter((c:any)=>c.path==='/api/unlock').length)).toBe(3);
 expect(await page.evaluate(()=>(window as any).calls.filter((c:any)=>c.path==='/api/golive').at(-1).body.mic_name)).toBe('Test mic');
 await expect(page.getByRole('button',{name:'End session',exact:true})).toBeEnabled();
 await expect(page.getByText('3/4 confirmed',{exact:true})).toBeVisible();
 await expect(page.getByText('USB reported configured',{exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/studio-live.png',fullPage:true});
 await expect(page.getByRole('region',{name:'Meeting checks'})).toBeVisible();
 await page.getByRole('button',{name:'Mute microphone',exact:true}).click();
 await expect(page.getByRole('button',{name:'Unmute microphone',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Mute meeting audio',exact:true}).click();
 await expect(page.getByRole('button',{name:'Enable meeting audio',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'End session',exact:true}).click();
 await expect(page.getByRole('button',{name:'Go live',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Sessions',exact:true}).click();
 await expect(page.getByText('Test room',{exact:true})).toBeVisible();
});
